version: "3"
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    volumes:
      - ./mlruns:/tmp/mlruns
    working_dir: /tmp
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri mlruns --default-artifact-root mlruns --host 0.0.0.0 --port 5000
    restart: always